function [Sol, Var] = computeChargeIntervals(Sim, solverparams)
import scheduler.util7.*;
import scheduler.con7.*;

Var = getVarParam(Sim);
[A1, b1, nConst1, descr1, eq1] = getCon1(Sim,Var);
[A2, b2, nConst2, descr2, eq2] = getCon2(Sim,Var);
[A3, b3, nConst3, descr3, eq3] = getCon3(Sim,Var);
Q = getObj(Sim,Var);
A = [...
     A1;...
     A2;...
     A3;...
     ];
b = [...
     b1;...
     b2;...
     b3;...
     ];
eq = [...
     eq1;...
     eq2;...
     eq3;...
     ]; 

vtype = repmat('C',[Var.nVar,1]);
model.vtype = vtype;
model.Q = Q;
model.A = A;
model.rhs = b;
model.sense = eq;
Sol = gurobi(model,struct(solverparams{:}));

end